import Telnyx from 'telnyx';
import { DIAL_TIMEOUT_SECS } from './config.js';

const need = (k) => { const v = process.env[k]; if (!v) throw new Error(k + ' is not set (server/.env)'); return v; };
const base = () => need('PUBLIC_URL').replace(/[/]$/, '');

let client;
/** Lazy so the server boots (health, login) before the Telnyx keys land in .env. */
export const telnyx = () => (client ??= new Telnyx({ apiKey: need('TELNYX_API_KEY'), publicKey: need('TELNYX_PUBLIC_KEY') }));

export const encodeState = (obj) => Buffer.from(JSON.stringify(obj)).toString('base64');
export const decodeState = (s) => { try { return s ? JSON.parse(Buffer.from(s, 'base64').toString('utf8')) : null; } catch { return null; } };

const common = () => ({
  connection_id: need('TELNYX_CONNECTION_ID'),
  webhook_url: base() + '/webhooks/telnyx',
  answering_machine_detection: 'disabled', // plan s1: no AMD, voicemail counts as connected
});

/** Rep leg (plan s8): rings once, stays open all session, silence when idle so there is no
 *  ringback in his ear. Telnyx caps a leg at 4h (time_limit_secs max 14400): expect a
 *  Disconnected -> Reconnect roughly twice per shift. */
export async function dialRep({ to, from, userId }) {
  const { data } = await telnyx().calls.dial({
    ...common(), to, from, timeout_secs: 40, send_silence_when_idle: true,
    client_state: encodeState({ kind: 'rep', userId }),
  });
  return data.call_control_id;
}

/** One lead leg of a burst. */
export async function dialLead({ to, from, userId, burstId, leadId }) {
  const { data } = await telnyx().calls.dial({
    ...common(), to, from, timeout_secs: DIAL_TIMEOUT_SECS,
    client_state: encodeState({ kind: 'lead', userId, burstId, leadId }),
  });
  return data.call_control_id;
}

/** Hanging up a leg that already ended is routine in a race: log it, never throw. */
export async function hangup(id) {
  try { await telnyx().calls.actions.hangup(id, {}); }
  catch (e) { console.warn('hangup', String(id).slice(-8), e.message); }
}
// Rep-leg cues (server/public, generated by scripts/gen-sounds.mjs). Telnyx reports call.playback.ended on the leg.
const play = (leg, file, opts = {}) => telnyx().calls.actions.startPlayback(leg, { audio_url: base() + '/static/' + file, ...opts });
export const beep = (repLeg) => play(repLeg, 'beep.wav');                              // lead answered, bridging next
export const startTick = (repLeg) => play(repLeg, 'tick.wav', { loop: 'infinity' });   // leads are ringing
export const noAnswerTone = (repLeg) => play(repLeg, 'noanswer.wav');                  // burst over, nobody picked up
export const stopPlayback = (leg) => telnyx().calls.actions.stopPlayback(leg, { stop: 'all' })
  .catch((e) => console.warn('stopPlayback', String(leg).slice(-8), e.message));
export const bridge = (repLeg, leadLeg) =>
  // park_after_unbridge: without it Telnyx hangs up the rep leg too when the lead hangs up (plan s8: rep leg stays open all session).
  telnyx().calls.actions.bridge(repLeg, { call_control_id_to_bridge_with: leadLeg, prevent_double_bridge: true, park_after_unbridge: 'self' });
/** Dialpad during a bridged call. Tones sent on the rep leg are heard by the other end (IVR menus, extensions). */
export const sendDtmf = (leg, digits) => telnyx().calls.actions.sendDtmf(leg, { digits });

/** Browser audio (plan s9). One on-demand telephony credential per user, created on first use and
 *  kept forever; the browser only ever sees a 24h JWT minted from it, never the SIP password.
 *  Telnyx asks for ~5 s between creating a credential and logging in with its token. */
export async function ensureCredential(user) {
  if (user.telnyx_credential_id && user.sip_username) return { id: user.telnyx_credential_id, sip_username: user.sip_username, fresh: false };
  const { data } = await telnyx().telephonyCredentials.create({ connection_id: need('TELNYX_WEBRTC_CONNECTION_ID'), name: user.email });
  return { id: data.id, sip_username: data.sip_username, fresh: true };
}
export const webrtcToken = (credentialId) => telnyx().telephonyCredentials.createToken(credentialId);
export const sipDestination = (sipUsername) => `sip:${sipUsername}@sip.telnyx.com`;
